version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: Greenwez raw data
    tables:
      - name: sales
        description: raw data for sales
        identifier: raw_gz_sales
      - name: product
        description: raw data for product
        identifier: raw_gz_product
      - name: ship
        description: raw data for ship
        identifier: raw_gz_ship


