version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: Greenwez raw data
    tables:
      - name: sales
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        description: raw data for sales
        identifier: raw_gz_sales
        columns:
          - name: date_date
            description: purchase date
          - name: orders_id
            description: ship foreign key
          - name: pdt_id
            description: product foreign key
          - name: revenue
            description: purchase_price * quantity
          - name: quantity
            description: quatity purchased
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
      - name: product
        description: raw data for product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: price of the product
      - name: ship
        description: raw data for ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping price paid by customer
          - name: logcost
            description: preparation cost
          - name: ship_cost
            description: shipping fees paid by Greenwez 


