version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: Greenwez raw data
    tables:

      - name: sales
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        description: raw data for sales
        identifier: raw_gz_sales
        columns:
          - name: date_date
            description: purchase date
          - name: orders_id
            description: ship foreign key
          - name: pdt_id
            description: product foreign key
          - name: revenue
            description: purchase_price * quantity
          - name: quantity
            description: quatity purchased
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
      - name: product
        description: raw data for product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: price of the product
      - name: ship
        description: raw data for ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping price paid by customer
          - name: logcost
            description: preparation cost
          - name: ship_cost
            description: shipping fees paid by Greenwez 
      - name: adwords
        description: raw data for adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
            description: date of adwords campaign launch
          - name: paid_source
            description: campaign source from adwords
          - name: campaign_key
            description: primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
            description: adwords campaign name
          - name: ads_cost
            description: cost of ads campaign
          - name: impression
            description: number of impression per campaign 
          - name: click
            description: number of click per campaign
      - name: bing
        description: raw data for bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
            description: date of bing campaign launch
          - name: paid_source
            description: campaign source from bing
          - name: campaign_key
            description: primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
            description: bing campaign name
          - name: ads_cost
            description: cost of ads campaign
          - name: impression
            description: number of impression per campaign 
          - name: click
            description: number of click per campaign
      - name: criteo
        description: raw data for criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
            description: date of criteo campaign launch
          - name: paid_source
            description: campaign source from criteo
          - name: campaign_key
            description: primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
            description: criteo campaign name
          - name: ads_cost
            description: cost of ads campaign
          - name: impression
            description: number of impression per campaign 
          - name: click
            description: number of click per campaign   
      - name: facebook
        description: raw data for facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
            description: date of facebook campaign launch
          - name: paid_source
            description: campaign source from facebook
          - name: campaign_key
            description: primary key
            tests:
              - unique
              - not_null
          - name: camPGN_name
            description: facebook campaign name
          - name: ads_cost
            description: cost of ads campaign
          - name: impression
            description: number of impression per campaign 
          - name: click
            description: number of click per campaign 
